/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaApplication1;

//---------------Imports---------------//

import static JavaApplication1.javaConnect.DB_URL;
import static JavaApplication1.javaConnect.PASS;
import static JavaApplication1.javaConnect.USER;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.net.URI;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import javax.swing.ImageIcon;


//----------------------------------------//
public class Admin_Form extends javax.swing.JFrame {
 
	Connection conn=null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	
	public Admin_Form() {	// Creates new form Admin_Form
		initComponents();
		
		setExtendedState(JFrame.MAXIMIZED_BOTH);
		
		//---------------Main_form start button color set---------------//
		
			SakumaEkrans_Panel.show();
			SpeletajuInfo_Panel.hide();
			SpeluInfo_Panel.hide();
			MansProfils_Panel.hide();
			Drizuma_Panel.hide();
			ProgrammasInfo_Panel.hide();
	
			setColor(button_SakumaEkrans);
			resetColor(button_SpeletajuInfo);
			resetColor(button_SpeluInfo);
			resetColor(button_MansProfils);
			resetColor(button_Drizuma);
			resetColor(button_ProgrammasInfo);

			 // Indicators

			ind_SakumaEkrans.setOpaque(true);
			ind_SpeletajuInfo.setOpaque(false);
			ind_SpeluInfo.setOpaque(false);
			ind_MansProfils.setOpaque(false);
			ind_ProgrammasInfo.setOpaque(false);
			ind_Drizuma.setOpaque(false);
				
		//-----------------------------------------------------------------------------//
		
		this.setLocationRelativeTo(null);
		
		try 
		{	
			conn = DriverManager.getConnection(DB_URL, USER, PASS);
		} 
		
		catch (SQLException ex) 
		{
			Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
		}
		
		Update_table();	
	}
	
private void Update_table() {
	
	String insert = "select * from speletaji";
	
	try {
		pst = conn.prepareStatement(insert);   
		rs = pst.executeQuery();
		Table_Players.setModel(DbUtils.resultSetToTableModel(rs));
	}
	
	catch(Exception e) {
		JOptionPane.showMessageDialog(null, e);
	}
}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Panel = new javax.swing.JPanel();
        WhiteBar_Panel = new javax.swing.JPanel();
        Side_Panel = new javax.swing.JPanel();
        DFA_Logo = new javax.swing.JLabel();
        button_SakumaEkrans = new javax.swing.JPanel();
        ind_SakumaEkrans = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_SpeletajuInfo = new javax.swing.JPanel();
        ind_SpeletajuInfo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button_PievienotSpeletajus = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        button_RedigetSpeletajus = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        button_DzestSpeletajus = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        button_SpeluInfo = new javax.swing.JPanel();
        ind_SpeluInfo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        button_RedigetSpeles = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        button_PievienotSpeles = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        button_DzestSpeles = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        button_MansProfils = new javax.swing.JPanel();
        ind_MansProfils = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        button_Drizuma = new javax.swing.JPanel();
        ind_Drizuma = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        button_ProgrammasInfo = new javax.swing.JPanel();
        ind_ProgrammasInfo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        button_exit = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        SakumaEkrans_Panel = new javax.swing.JPanel();
        SpeletajuInfo_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Players = new javax.swing.JTable();
        SpeluInfo_Panel = new javax.swing.JPanel();
        MansProfils_Panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Drizuma_Panel = new javax.swing.JPanel();
        ProgrammasInfo_Panel = new javax.swing.JPanel();
        Programm_Info = new javax.swing.JLabel();
        NP_picture = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Instagram_icon = new javax.swing.JLabel();
        Facebook_icon = new javax.swing.JLabel();
        GitHub_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background_Panel.setBackground(new java.awt.Color(52, 73, 94));

        WhiteBar_Panel.setBackground(new java.awt.Color(255, 255, 255));
        WhiteBar_Panel.setPreferredSize(new java.awt.Dimension(6, 0));

        javax.swing.GroupLayout WhiteBar_PanelLayout = new javax.swing.GroupLayout(WhiteBar_Panel);
        WhiteBar_Panel.setLayout(WhiteBar_PanelLayout);
        WhiteBar_PanelLayout.setHorizontalGroup(
            WhiteBar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        WhiteBar_PanelLayout.setVerticalGroup(
            WhiteBar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Side_Panel.setBackground(new java.awt.Color(52, 152, 219));

        DFA_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DFA_Logo.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\DFA_Logo.png")); // NOI18N
        DFA_Logo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DFA_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        button_SakumaEkrans.setBackground(new java.awt.Color(52, 152, 219));
        button_SakumaEkrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_SakumaEkrans.setPreferredSize(new java.awt.Dimension(157, 50));
        button_SakumaEkrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_SakumaEkransMousePressed(evt);
            }
        });

        ind_SakumaEkrans.setBackground(new java.awt.Color(255, 255, 255));
        ind_SakumaEkrans.setOpaque(false);
        ind_SakumaEkrans.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_SakumaEkransLayout = new javax.swing.GroupLayout(ind_SakumaEkrans);
        ind_SakumaEkrans.setLayout(ind_SakumaEkransLayout);
        ind_SakumaEkransLayout.setHorizontalGroup(
            ind_SakumaEkransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_SakumaEkransLayout.setVerticalGroup(
            ind_SakumaEkransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sākuma ekrāns");

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\home-5-24.png")); // NOI18N

        javax.swing.GroupLayout button_SakumaEkransLayout = new javax.swing.GroupLayout(button_SakumaEkrans);
        button_SakumaEkrans.setLayout(button_SakumaEkransLayout);
        button_SakumaEkransLayout.setHorizontalGroup(
            button_SakumaEkransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_SakumaEkransLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_SakumaEkrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_SakumaEkransLayout.setVerticalGroup(
            button_SakumaEkransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_SakumaEkrans, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_SakumaEkransLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_SakumaEkransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_SakumaEkransLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        button_SpeletajuInfo.setBackground(new java.awt.Color(52, 152, 219));
        button_SpeletajuInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_SpeletajuInfo.setPreferredSize(new java.awt.Dimension(157, 50));
        button_SpeletajuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_SpeletajuInfoMousePressed(evt);
            }
        });

        ind_SpeletajuInfo.setBackground(new java.awt.Color(255, 255, 255));
        ind_SpeletajuInfo.setOpaque(false);
        ind_SpeletajuInfo.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_SpeletajuInfoLayout = new javax.swing.GroupLayout(ind_SpeletajuInfo);
        ind_SpeletajuInfo.setLayout(ind_SpeletajuInfoLayout);
        ind_SpeletajuInfoLayout.setHorizontalGroup(
            ind_SpeletajuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_SpeletajuInfoLayout.setVerticalGroup(
            ind_SpeletajuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Speletāju info");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\info-24.png")); // NOI18N

        javax.swing.GroupLayout button_SpeletajuInfoLayout = new javax.swing.GroupLayout(button_SpeletajuInfo);
        button_SpeletajuInfo.setLayout(button_SpeletajuInfoLayout);
        button_SpeletajuInfoLayout.setHorizontalGroup(
            button_SpeletajuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_SpeletajuInfoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_SpeletajuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        button_SpeletajuInfoLayout.setVerticalGroup(
            button_SpeletajuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_SpeletajuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_SpeletajuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_SpeletajuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_SpeletajuInfoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        button_PievienotSpeletajus.setBackground(new java.awt.Color(52, 152, 219));
        button_PievienotSpeletajus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_PievienotSpeletajus.setPreferredSize(new java.awt.Dimension(157, 50));
        button_PievienotSpeletajus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_PievienotSpeletajusMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pievienot spēlētājus");

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\plus-4-16.png")); // NOI18N

        javax.swing.GroupLayout button_PievienotSpeletajusLayout = new javax.swing.GroupLayout(button_PievienotSpeletajus);
        button_PievienotSpeletajus.setLayout(button_PievienotSpeletajusLayout);
        button_PievienotSpeletajusLayout.setHorizontalGroup(
            button_PievienotSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_PievienotSpeletajusLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_PievienotSpeletajusLayout.setVerticalGroup(
            button_PievienotSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_PievienotSpeletajusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_PievienotSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        button_RedigetSpeletajus.setBackground(new java.awt.Color(52, 152, 219));
        button_RedigetSpeletajus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_RedigetSpeletajus.setPreferredSize(new java.awt.Dimension(157, 50));
        button_RedigetSpeletajus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_RedigetSpeletajusMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rediģēt spēlētājus");

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\wrench-16.png")); // NOI18N

        javax.swing.GroupLayout button_RedigetSpeletajusLayout = new javax.swing.GroupLayout(button_RedigetSpeletajus);
        button_RedigetSpeletajus.setLayout(button_RedigetSpeletajusLayout);
        button_RedigetSpeletajusLayout.setHorizontalGroup(
            button_RedigetSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_RedigetSpeletajusLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_RedigetSpeletajusLayout.setVerticalGroup(
            button_RedigetSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_RedigetSpeletajusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_RedigetSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        button_DzestSpeletajus.setBackground(new java.awt.Color(52, 152, 219));
        button_DzestSpeletajus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_DzestSpeletajus.setPreferredSize(new java.awt.Dimension(157, 50));
        button_DzestSpeletajus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_DzestSpeletajusMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Dzēst spēlētājus");

        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\x-mark-3-16.png")); // NOI18N

        javax.swing.GroupLayout button_DzestSpeletajusLayout = new javax.swing.GroupLayout(button_DzestSpeletajus);
        button_DzestSpeletajus.setLayout(button_DzestSpeletajusLayout);
        button_DzestSpeletajusLayout.setHorizontalGroup(
            button_DzestSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_DzestSpeletajusLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_DzestSpeletajusLayout.setVerticalGroup(
            button_DzestSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_DzestSpeletajusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_DzestSpeletajusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        button_SpeluInfo.setBackground(new java.awt.Color(52, 152, 219));
        button_SpeluInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_SpeluInfo.setPreferredSize(new java.awt.Dimension(157, 50));
        button_SpeluInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_SpeluInfoMousePressed(evt);
            }
        });

        ind_SpeluInfo.setBackground(new java.awt.Color(255, 255, 255));
        ind_SpeluInfo.setOpaque(false);
        ind_SpeluInfo.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_SpeluInfoLayout = new javax.swing.GroupLayout(ind_SpeluInfo);
        ind_SpeluInfo.setLayout(ind_SpeluInfoLayout);
        ind_SpeluInfoLayout.setHorizontalGroup(
            ind_SpeluInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_SpeluInfoLayout.setVerticalGroup(
            ind_SpeluInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Spēļu info");

        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\planner-24.png")); // NOI18N

        javax.swing.GroupLayout button_SpeluInfoLayout = new javax.swing.GroupLayout(button_SpeluInfo);
        button_SpeluInfo.setLayout(button_SpeluInfoLayout);
        button_SpeluInfoLayout.setHorizontalGroup(
            button_SpeluInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_SpeluInfoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_SpeluInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        button_SpeluInfoLayout.setVerticalGroup(
            button_SpeluInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_SpeluInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_SpeluInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_SpeluInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_SpeluInfoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel21)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        button_RedigetSpeles.setBackground(new java.awt.Color(52, 152, 219));
        button_RedigetSpeles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_RedigetSpeles.setPreferredSize(new java.awt.Dimension(157, 50));
        button_RedigetSpeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_RedigetSpelesMousePressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Rediģēt spēles");

        jLabel26.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\wrench-16.png")); // NOI18N

        javax.swing.GroupLayout button_RedigetSpelesLayout = new javax.swing.GroupLayout(button_RedigetSpeles);
        button_RedigetSpeles.setLayout(button_RedigetSpelesLayout);
        button_RedigetSpelesLayout.setHorizontalGroup(
            button_RedigetSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_RedigetSpelesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_RedigetSpelesLayout.setVerticalGroup(
            button_RedigetSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_RedigetSpelesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_RedigetSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        button_PievienotSpeles.setBackground(new java.awt.Color(52, 152, 219));
        button_PievienotSpeles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_PievienotSpeles.setPreferredSize(new java.awt.Dimension(157, 50));
        button_PievienotSpeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_PievienotSpelesMousePressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Pievienot spēles");

        jLabel28.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\plus-4-16.png")); // NOI18N

        javax.swing.GroupLayout button_PievienotSpelesLayout = new javax.swing.GroupLayout(button_PievienotSpeles);
        button_PievienotSpeles.setLayout(button_PievienotSpelesLayout);
        button_PievienotSpelesLayout.setHorizontalGroup(
            button_PievienotSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_PievienotSpelesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_PievienotSpelesLayout.setVerticalGroup(
            button_PievienotSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_PievienotSpelesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_PievienotSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        button_DzestSpeles.setBackground(new java.awt.Color(52, 152, 219));
        button_DzestSpeles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_DzestSpeles.setPreferredSize(new java.awt.Dimension(157, 50));
        button_DzestSpeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_DzestSpelesMousePressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dzēst spēles");

        jLabel24.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\16x\\x-mark-3-16.png")); // NOI18N

        javax.swing.GroupLayout button_DzestSpelesLayout = new javax.swing.GroupLayout(button_DzestSpeles);
        button_DzestSpeles.setLayout(button_DzestSpelesLayout);
        button_DzestSpelesLayout.setHorizontalGroup(
            button_DzestSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_DzestSpelesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_DzestSpelesLayout.setVerticalGroup(
            button_DzestSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_DzestSpelesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_DzestSpelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        button_MansProfils.setBackground(new java.awt.Color(52, 152, 219));
        button_MansProfils.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_MansProfils.setPreferredSize(new java.awt.Dimension(157, 50));
        button_MansProfils.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_MansProfilsMousePressed(evt);
            }
        });

        ind_MansProfils.setBackground(new java.awt.Color(255, 255, 255));
        ind_MansProfils.setOpaque(false);
        ind_MansProfils.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_MansProfilsLayout = new javax.swing.GroupLayout(ind_MansProfils);
        ind_MansProfils.setLayout(ind_MansProfilsLayout);
        ind_MansProfilsLayout.setHorizontalGroup(
            ind_MansProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_MansProfilsLayout.setVerticalGroup(
            ind_MansProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mans profils");

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\user-4-24.png")); // NOI18N

        javax.swing.GroupLayout button_MansProfilsLayout = new javax.swing.GroupLayout(button_MansProfils);
        button_MansProfils.setLayout(button_MansProfilsLayout);
        button_MansProfilsLayout.setHorizontalGroup(
            button_MansProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_MansProfilsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_MansProfils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_MansProfilsLayout.setVerticalGroup(
            button_MansProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_MansProfils, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_MansProfilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_MansProfilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_MansProfilsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        button_Drizuma.setBackground(new java.awt.Color(52, 152, 219));
        button_Drizuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Drizuma.setPreferredSize(new java.awt.Dimension(157, 50));
        button_Drizuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_DrizumaMousePressed(evt);
            }
        });

        ind_Drizuma.setBackground(new java.awt.Color(255, 255, 255));
        ind_Drizuma.setOpaque(false);
        ind_Drizuma.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_DrizumaLayout = new javax.swing.GroupLayout(ind_Drizuma);
        ind_Drizuma.setLayout(ind_DrizumaLayout);
        ind_DrizumaLayout.setHorizontalGroup(
            ind_DrizumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_DrizumaLayout.setVerticalGroup(
            ind_DrizumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Drīzumā");

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\plus-8-24.png")); // NOI18N

        javax.swing.GroupLayout button_DrizumaLayout = new javax.swing.GroupLayout(button_Drizuma);
        button_Drizuma.setLayout(button_DrizumaLayout);
        button_DrizumaLayout.setHorizontalGroup(
            button_DrizumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_DrizumaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_Drizuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_DrizumaLayout.setVerticalGroup(
            button_DrizumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_Drizuma, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_DrizumaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(button_DrizumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(button_DrizumaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        button_ProgrammasInfo.setBackground(new java.awt.Color(52, 152, 219));
        button_ProgrammasInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_ProgrammasInfo.setPreferredSize(new java.awt.Dimension(157, 50));
        button_ProgrammasInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_ProgrammasInfoMousePressed(evt);
            }
        });

        ind_ProgrammasInfo.setBackground(new java.awt.Color(255, 255, 255));
        ind_ProgrammasInfo.setOpaque(false);
        ind_ProgrammasInfo.setPreferredSize(new java.awt.Dimension(7, 0));

        javax.swing.GroupLayout ind_ProgrammasInfoLayout = new javax.swing.GroupLayout(ind_ProgrammasInfo);
        ind_ProgrammasInfo.setLayout(ind_ProgrammasInfoLayout);
        ind_ProgrammasInfoLayout.setHorizontalGroup(
            ind_ProgrammasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        ind_ProgrammasInfoLayout.setVerticalGroup(
            ind_ProgrammasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Programmas info");

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\info-24.png")); // NOI18N

        javax.swing.GroupLayout button_ProgrammasInfoLayout = new javax.swing.GroupLayout(button_ProgrammasInfo);
        button_ProgrammasInfo.setLayout(button_ProgrammasInfoLayout);
        button_ProgrammasInfoLayout.setHorizontalGroup(
            button_ProgrammasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_ProgrammasInfoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ind_ProgrammasInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        button_ProgrammasInfoLayout.setVerticalGroup(
            button_ProgrammasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_ProgrammasInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(button_ProgrammasInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(button_ProgrammasInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button_exit.setBackground(new java.awt.Color(52, 73, 94));
        button_exit.setForeground(new java.awt.Color(230, 126, 34));
        button_exit.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\exit-24.png")); // NOI18N
        button_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Side_PanelLayout = new javax.swing.GroupLayout(Side_Panel);
        Side_Panel.setLayout(Side_PanelLayout);
        Side_PanelLayout.setHorizontalGroup(
            Side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_SakumaEkrans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_SpeletajuInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_MansProfils, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_Drizuma, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addGroup(Side_PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DFA_Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(button_exit)
                .addGap(25, 25, 25))
            .addComponent(button_ProgrammasInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_PievienotSpeletajus, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_RedigetSpeletajus, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_DzestSpeletajus, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_PievienotSpeles, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_RedigetSpeles, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_DzestSpeles, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
            .addComponent(button_SpeluInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );
        Side_PanelLayout.setVerticalGroup(
            Side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_SakumaEkrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_SpeletajuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_PievienotSpeletajus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_RedigetSpeletajus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_DzestSpeletajus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_SpeluInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_PievienotSpeles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_RedigetSpeles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_DzestSpeles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(button_MansProfils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Drizuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(button_ProgrammasInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(Side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DFA_Logo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_exit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );

        SakumaEkrans_Panel.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout SakumaEkrans_PanelLayout = new javax.swing.GroupLayout(SakumaEkrans_Panel);
        SakumaEkrans_Panel.setLayout(SakumaEkrans_PanelLayout);
        SakumaEkrans_PanelLayout.setHorizontalGroup(
            SakumaEkrans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2686, Short.MAX_VALUE)
        );
        SakumaEkrans_PanelLayout.setVerticalGroup(
            SakumaEkrans_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1335, Short.MAX_VALUE)
        );

        SpeletajuInfo_Panel.setBackground(new java.awt.Color(51, 255, 102));

        Table_Players.setAutoCreateRowSorter(true);
        Table_Players.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table_Players.setForeground(new java.awt.Color(44, 62, 80));
        Table_Players.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Players.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Table_Players.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Table_Players.setRowHeight(25);
        Table_Players.setSelectionBackground(new java.awt.Color(46, 204, 113));
        Table_Players.setSelectionForeground(new java.awt.Color(44, 62, 80));
        Table_Players.setShowHorizontalLines(false);
        Table_Players.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Players);

        javax.swing.GroupLayout SpeletajuInfo_PanelLayout = new javax.swing.GroupLayout(SpeletajuInfo_Panel);
        SpeletajuInfo_Panel.setLayout(SpeletajuInfo_PanelLayout);
        SpeletajuInfo_PanelLayout.setHorizontalGroup(
            SpeletajuInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeletajuInfo_PanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1323, Short.MAX_VALUE))
        );
        SpeletajuInfo_PanelLayout.setVerticalGroup(
            SpeletajuInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeletajuInfo_PanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(725, Short.MAX_VALUE))
        );

        SpeluInfo_Panel.setBackground(new java.awt.Color(255, 204, 204));
        SpeluInfo_Panel.setPreferredSize(new java.awt.Dimension(2375, 1323));

        javax.swing.GroupLayout SpeluInfo_PanelLayout = new javax.swing.GroupLayout(SpeluInfo_Panel);
        SpeluInfo_Panel.setLayout(SpeluInfo_PanelLayout);
        SpeluInfo_PanelLayout.setHorizontalGroup(
            SpeluInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2686, Short.MAX_VALUE)
        );
        SpeluInfo_PanelLayout.setVerticalGroup(
            SpeluInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1335, Short.MAX_VALUE)
        );

        MansProfils_Panel.setBackground(new java.awt.Color(0, 153, 153));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Ienākt / Reģistrēties");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout MansProfils_PanelLayout = new javax.swing.GroupLayout(MansProfils_Panel);
        MansProfils_Panel.setLayout(MansProfils_PanelLayout);
        MansProfils_PanelLayout.setHorizontalGroup(
            MansProfils_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MansProfils_PanelLayout.createSequentialGroup()
                .addGap(558, 558, 558)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1876, Short.MAX_VALUE))
        );
        MansProfils_PanelLayout.setVerticalGroup(
            MansProfils_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MansProfils_PanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1092, Short.MAX_VALUE))
        );

        Drizuma_Panel.setBackground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout Drizuma_PanelLayout = new javax.swing.GroupLayout(Drizuma_Panel);
        Drizuma_Panel.setLayout(Drizuma_PanelLayout);
        Drizuma_PanelLayout.setHorizontalGroup(
            Drizuma_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2375, Short.MAX_VALUE)
        );
        Drizuma_PanelLayout.setVerticalGroup(
            Drizuma_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1323, Short.MAX_VALUE)
        );

        ProgrammasInfo_Panel.setBackground(new java.awt.Color(52, 73, 94));

        Programm_Info.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\Programmas_info photoshop file.png")); // NOI18N

        NP_picture.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\36988094_2043389069065588_7157785130197581824_n1111.png")); // NOI18N

        jPanel1.setBackground(null);
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(null);

        Instagram_icon.setIcon(new javax.swing.ImageIcon("D:\\Users\\user\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\instagram (2).png")); // NOI18N
        Instagram_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instagram_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Instagram_iconMousePressed(evt);
            }
        });
        jPanel1.add(Instagram_icon);
        Instagram_icon.setBounds(580, 400, 64, 64);

        Facebook_icon.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\facebook (2).png")); // NOI18N
        Facebook_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Facebook_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Facebook_iconMousePressed(evt);
            }
        });
        jPanel1.add(Facebook_icon);
        Facebook_icon.setBounds(510, 400, 64, 64);

        GitHub_icon.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\github (2).png")); // NOI18N
        GitHub_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GitHub_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GitHub_iconMousePressed(evt);
            }
        });
        jPanel1.add(GitHub_icon);
        GitHub_icon.setBounds(650, 400, 64, 64);

        jLabel2.setForeground(new java.awt.Color(60, 63, 65));
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Users\\User\\Documents\\NetBeansProjects\\JavaApplication1\\images for project\\Info par mani.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 0, 736, 503);

        javax.swing.GroupLayout ProgrammasInfo_PanelLayout = new javax.swing.GroupLayout(ProgrammasInfo_Panel);
        ProgrammasInfo_Panel.setLayout(ProgrammasInfo_PanelLayout);
        ProgrammasInfo_PanelLayout.setHorizontalGroup(
            ProgrammasInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgrammasInfo_PanelLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(ProgrammasInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Programm_Info)
                    .addGroup(ProgrammasInfo_PanelLayout.createSequentialGroup()
                        .addComponent(NP_picture)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(145, 145, 145))
        );
        ProgrammasInfo_PanelLayout.setVerticalGroup(
            ProgrammasInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgrammasInfo_PanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(Programm_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProgrammasInfo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NP_picture)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(476, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(SakumaEkrans_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SpeletajuInfo_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SpeluInfo_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(MansProfils_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Drizuma_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ProgrammasInfo_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SakumaEkrans_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SpeletajuInfo_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MansProfils_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Drizuma_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgrammasInfo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SpeluInfo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 2686, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SakumaEkrans_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SpeletajuInfo_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MansProfils_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Drizuma_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgrammasInfo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SpeluInfo_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Background_PanelLayout = new javax.swing.GroupLayout(Background_Panel);
        Background_Panel.setLayout(Background_PanelLayout);
        Background_PanelLayout.setHorizontalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addComponent(Side_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(WhiteBar_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1)
                .addGap(0, 0, 0))
        );
        Background_PanelLayout.setVerticalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Side_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(WhiteBar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1335, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_SakumaEkransMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SakumaEkransMousePressed

         SakumaEkrans_Panel.show();
         SpeletajuInfo_Panel.hide();
	SpeluInfo_Panel.hide();
         MansProfils_Panel.hide();
         Drizuma_Panel.hide();
         ProgrammasInfo_Panel.hide();
	
         setColor(button_SakumaEkrans);
         resetColor(button_SpeletajuInfo);
	resetColor(button_SpeluInfo);
         resetColor(button_MansProfils);
         resetColor(button_Drizuma);
         resetColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(true);
         ind_SpeletajuInfo.setOpaque(false);
	ind_SpeluInfo.setOpaque(false);
         ind_MansProfils.setOpaque(false);
         ind_ProgrammasInfo.setOpaque(false);
	ind_Drizuma.setOpaque(false);
    }//GEN-LAST:event_button_SakumaEkransMousePressed

    private void button_SpeletajuInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SpeletajuInfoMousePressed

         SakumaEkrans_Panel.hide();
         SpeletajuInfo_Panel.show();
	SpeluInfo_Panel.hide();
         MansProfils_Panel.hide();
         Drizuma_Panel.hide();
         ProgrammasInfo_Panel.hide();
	
	resetColor(button_SakumaEkrans);
         setColor(button_SpeletajuInfo);
         resetColor(button_SpeluInfo);
         resetColor(button_MansProfils);
         resetColor(button_Drizuma);
         resetColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(false);
         ind_SpeletajuInfo.setOpaque(true);
	ind_SpeluInfo.setOpaque(false);
         ind_MansProfils.setOpaque(false);
	ind_ProgrammasInfo.setOpaque(false);
         ind_Drizuma.setOpaque(false);
    }//GEN-LAST:event_button_SpeletajuInfoMousePressed

    private void button_MansProfilsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MansProfilsMousePressed

         SakumaEkrans_Panel.hide();
         SpeletajuInfo_Panel.hide();
	SpeluInfo_Panel.hide();
         MansProfils_Panel.show();
         Drizuma_Panel.hide();
         ProgrammasInfo_Panel.hide();
	
	resetColor(button_SakumaEkrans);
         resetColor(button_SpeletajuInfo);
         resetColor(button_SpeluInfo);
         setColor(button_MansProfils);
         resetColor(button_Drizuma);
         resetColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(false);
         ind_SpeletajuInfo.setOpaque(false);
	ind_SpeluInfo.setOpaque(false);
         ind_MansProfils.setOpaque(true);
	ind_ProgrammasInfo.setOpaque(false);
         ind_Drizuma.setOpaque(false);
    }//GEN-LAST:event_button_MansProfilsMousePressed

    private void button_DrizumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DrizumaMousePressed

         SakumaEkrans_Panel.hide();
         SpeletajuInfo_Panel.hide();
	SpeluInfo_Panel.hide();
         MansProfils_Panel.hide();
         Drizuma_Panel.show();
         ProgrammasInfo_Panel.hide();
	
	resetColor(button_SakumaEkrans);
         resetColor(button_SpeletajuInfo);
         resetColor(button_SpeluInfo);
         resetColor(button_MansProfils);
         setColor(button_Drizuma);
         resetColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(false);
         ind_SpeletajuInfo.setOpaque(false);
	ind_SpeluInfo.setOpaque(false);
         ind_MansProfils.setOpaque(false);
	ind_ProgrammasInfo.setOpaque(false);
         ind_Drizuma.setOpaque(true);
    }//GEN-LAST:event_button_DrizumaMousePressed

    private void button_ProgrammasInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ProgrammasInfoMousePressed

         SakumaEkrans_Panel.hide();
         SpeletajuInfo_Panel.hide();
	SpeluInfo_Panel.hide();
         MansProfils_Panel.hide();
         Drizuma_Panel.hide();
         ProgrammasInfo_Panel.show();
	
	resetColor(button_SakumaEkrans);
         resetColor(button_SpeletajuInfo);
         resetColor(button_SpeluInfo);
         resetColor(button_MansProfils);
         resetColor(button_Drizuma);
         setColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(false);
         ind_SpeletajuInfo.setOpaque(false);
	ind_SpeluInfo.setOpaque(false);
         ind_MansProfils.setOpaque(false);
	ind_ProgrammasInfo.setOpaque(true);
         ind_Drizuma.setOpaque(false);

    }//GEN-LAST:event_button_ProgrammasInfoMousePressed

    private void button_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exitMousePressed
        this.dispose();
    }//GEN-LAST:event_button_exitMousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Login_Form s = new Login_Form();		// Shows new Form - Player_info
        s.setVisible(true);
    }//GEN-LAST:event_jButton2MousePressed

    private void Instagram_iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Instagram_iconMousePressed
        try
        {
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/nawris_p/"));
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something wrong with URI link!");
        }
    }//GEN-LAST:event_Instagram_iconMousePressed

    private void Facebook_iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Facebook_iconMousePressed
        try
        {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/nauris.putans.7"));
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something wrong with URI link!");
        }
    }//GEN-LAST:event_Facebook_iconMousePressed

    private void GitHub_iconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GitHub_iconMousePressed
        try
        {
            Desktop.getDesktop().browse(new URI("https://github.com/Nauris-Putans"));
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Something wrong with URI link!");
        }
    }//GEN-LAST:event_GitHub_iconMousePressed

    private void button_PievienotSpeletajusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_PievienotSpeletajusMousePressed
		
    }//GEN-LAST:event_button_PievienotSpeletajusMousePressed

    private void button_RedigetSpeletajusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_RedigetSpeletajusMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_RedigetSpeletajusMousePressed

    private void button_DzestSpeletajusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DzestSpeletajusMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_DzestSpeletajusMousePressed

    private void button_SpeluInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SpeluInfoMousePressed
        
	SakumaEkrans_Panel.hide();
         SpeletajuInfo_Panel.hide();
	SpeluInfo_Panel.show();
         MansProfils_Panel.hide();
         Drizuma_Panel.hide();
         ProgrammasInfo_Panel.hide();
	
	resetColor(button_SakumaEkrans);
         resetColor(button_SpeletajuInfo);
         setColor(button_SpeluInfo);
         resetColor(button_MansProfils);
         resetColor(button_Drizuma);
         resetColor(button_ProgrammasInfo);

         // Indicators

         ind_SakumaEkrans.setOpaque(false);
         ind_SpeletajuInfo.setOpaque(false);
	ind_SpeluInfo.setOpaque(true);
         ind_MansProfils.setOpaque(false);
	ind_ProgrammasInfo.setOpaque(false);
         ind_Drizuma.setOpaque(false);
    }//GEN-LAST:event_button_SpeluInfoMousePressed

    private void button_DzestSpelesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DzestSpelesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_DzestSpelesMousePressed

    private void button_RedigetSpelesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_RedigetSpelesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_RedigetSpelesMousePressed

    private void button_PievienotSpelesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_PievienotSpelesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_PievienotSpelesMousePressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Admin_Form().setVisible(true);
			}
		});
	}
	
	void setColor(JPanel panel) {
		panel.setBackground(new Color(86,65,118));
	}
	
	void resetColor(JPanel panel) {
		panel.setBackground(new Color(52,152,219));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JLabel DFA_Logo;
    public javax.swing.JPanel Drizuma_Panel;
    private javax.swing.JLabel Facebook_icon;
    private javax.swing.JLabel GitHub_icon;
    private javax.swing.JLabel Instagram_icon;
    public javax.swing.JPanel MansProfils_Panel;
    private javax.swing.JLabel NP_picture;
    private javax.swing.JLabel Programm_Info;
    public javax.swing.JPanel ProgrammasInfo_Panel;
    public javax.swing.JPanel SakumaEkrans_Panel;
    private javax.swing.JPanel Side_Panel;
    public javax.swing.JPanel SpeletajuInfo_Panel;
    public javax.swing.JPanel SpeluInfo_Panel;
    public javax.swing.JTable Table_Players;
    private javax.swing.JPanel WhiteBar_Panel;
    private javax.swing.JPanel button_Drizuma;
    private javax.swing.JPanel button_DzestSpeles;
    private javax.swing.JPanel button_DzestSpeletajus;
    private javax.swing.JPanel button_MansProfils;
    private javax.swing.JPanel button_PievienotSpeles;
    private javax.swing.JPanel button_PievienotSpeletajus;
    private javax.swing.JPanel button_ProgrammasInfo;
    private javax.swing.JPanel button_RedigetSpeles;
    private javax.swing.JPanel button_RedigetSpeletajus;
    private javax.swing.JPanel button_SakumaEkrans;
    private javax.swing.JPanel button_SpeletajuInfo;
    private javax.swing.JPanel button_SpeluInfo;
    private javax.swing.JButton button_exit;
    private javax.swing.JPanel ind_Drizuma;
    private javax.swing.JPanel ind_MansProfils;
    private javax.swing.JPanel ind_ProgrammasInfo;
    private javax.swing.JPanel ind_SakumaEkrans;
    private javax.swing.JPanel ind_SpeletajuInfo;
    private javax.swing.JPanel ind_SpeluInfo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
